{
 "cells": [
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": None,
   "id": "6778f8ff-16af-4b1b-8e4c-e25f2afc83a0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==========  To-Do List Manager ==========\n",
      "1. Add Task\n",
      "2. View Tasks\n",
      "3. Edit/Update Task\n",
      "4. Delete Task\n",
      "5. Exit and Save\n",
      "============================================\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import os\n",
    "from datetime import datetime\n",
    "# ==============================================================================\n",
    "# 1. OOP: Class และ Encapsulation (20%)\n",
    "# ==============================================================================\n",
    "\n",
    "class Task:\n",
    "    \"\"\"แทนรายการ To-Do List แต่ละรายการ\"\"\"\n",
    "    \n",
    "    def __init__(self, description, due_date=None, completed=False):\n",
    "        # Encapsulation: ใช้ _ เพื่อระบุ attributes ภายใน\n",
    "        self._description = description\n",
    "        self._due_date = due_date\n",
    "        self._completed = completed\n",
    "        \n",
    "    # Getter methods (แสดง Encapsulation)\n",
    "    def get_description(self):\n",
    "        return self._description\n",
    "\n",
    "    def get_due_date(self):\n",
    "        return self._due_date\n",
    "\n",
    "    def is_completed(self):\n",
    "        return self._completed\n",
    "\n",
    "    # Setter method\n",
    "    def mark_completed(self, status=True):\n",
    "        \"\"\"ตั้งค่าสถานะการทำเสร็จ\"\"\"\n",
    "        self._completed = status\n",
    "\n",
    "    def update_description(self, new_desc):\n",
    "        \"\"\"อัปเดตคำอธิบายงาน\"\"\"\n",
    "        self._description = new_desc\n",
    "\n",
    "    def update_due_date(self, new_date):\n",
    "        \"\"\"อัปเดตวันครบกำหนด\"\"\"\n",
    "        self._due_date = new_date\n",
    "        \n",
    "    def __str__(self):\n",
    "        \"\"\"กำหนดรูปแบบการแสดงผลของ object\"\"\"\n",
    "        status = \" DONE\" if self._completed else \" PENDING\"\n",
    "        date_str = f\" (Due: {self._due_date})\" if self._due_date else \"\"\n",
    "        return f\"[{status}] {self._description}{date_str}\"\n",
    "        \n",
    "    def to_dict(self):\n",
    "        \"\"\"แปลง Task object เป็น Dictionary สำหรับบันทึกใน JSON\"\"\"\n",
    "        return {\n",
    "            \"description\": self._description,\n",
    "            \"due_date\": self._due_date,\n",
    "            \"completed\": self._completed\n",
    "        }\n",
    "\n",
    "    @staticmethod\n",
    "    def from_dict(data):\n",
    "        \"\"\"สร้าง Task object จาก Dictionary ที่โหลดมาจาก JSON\"\"\"\n",
    "        return Task(\n",
    "            description=data['description'],\n",
    "            due_date=data['due_date'],\n",
    "            completed=data['completed']\n",
    "        )\n",
    "\n",
    "# ==============================================================================\n",
    "# 2. File Handling (60%)\n",
    "# ==============================================================================\n",
    "\n",
    "FILE_NAME = \"tasks.json\"\n",
    "\n",
    "def save_tasks(tasks):\n",
    "    \"\"\"บันทึกรายการ Task ลงในไฟล์ JSON\"\"\"\n",
    "    data_to_save = [task.to_dict() for task in tasks]\n",
    "    try:\n",
    "        with open(FILE_NAME, 'w', encoding='utf-8') as f:\n",
    "            json.dump(data_to_save, f, indent=4)\n",
    "        return True\n",
    "    except IOError as e:\n",
    "        print(f\" Error saving file: {e}\")\n",
    "        return False\n",
    "\n",
    "def load_tasks():\n",
    "    \"\"\"โหลดรายการ Task จากไฟล์ JSON\"\"\"\n",
    "    if not os.path.exists(FILE_NAME):\n",
    "        return []\n",
    "    \n",
    "    try:\n",
    "        with open(FILE_NAME, 'r', encoding='utf-8') as f:\n",
    "            data = json.load(f)\n",
    "            # โครงสร้างข้อมูล: ใช้ List และ Dictionary\n",
    "            return [Task.from_dict(item) for item in data]\n",
    "    except (IOError, json.JSONDecodeError) as e:\n",
    "        print(f\" Error loading file or decoding JSON: {e}. Starting with an empty list.\")\n",
    "        return []\n",
    "\n",
    "# ==============================================================================\n",
    "# 3. Core Logic Functions (60%)\n",
    "# ==============================================================================\n",
    "\n",
    "def add_task(tasks):\n",
    "    \"\"\"เพิ่ม Task ใหม่เข้าไปในรายการ\"\"\"\n",
    "    description = input(\" Enter task description: \").strip()\n",
    "    if not description:\n",
    "        print(\" Task description cannot be empty.\")\n",
    "        return\n",
    "        \n",
    "    due_date = input(\"Enter due date (YYYY-MM-DD, optional): \").strip()\n",
    "    \n",
    "    # ตรวจสอบรูปแบบวันที่ (Conditionals)\n",
    "    if due_date:\n",
    "        try:\n",
    "            datetime.strptime(due_date, \"%Y-%m-%d\")\n",
    "        except ValueError:\n",
    "            print(\" Invalid date format. Task added without a due date.\")\n",
    "            due_date = None\n",
    "            \n",
    "    new_task = Task(description, due_date)\n",
    "    tasks.append(new_task)\n",
    "    print(f\" Task '{description}' added.\")\n",
    "    save_tasks(tasks)\n",
    "\n",
    "def view_tasks(tasks):\n",
    "    \"\"\"แสดงรายการ Task ทั้งหมด\"\"\"\n",
    "    if not tasks:\n",
    "        print(\"\\n Your To-Do List is empty!\")\n",
    "        return\n",
    "\n",
    "    print(\"\\n---  Current To-Do List ---\")\n",
    "    # Loops: ใช้ enumerate เพื่อแสดงลำดับ\n",
    "    for index, task in enumerate(tasks):\n",
    "        print(f\"[{index + 1}] {task}\")\n",
    "    print(\"----------------------------\\n\")\n",
    "\n",
    "def edit_task(tasks):\n",
    "    \"\"\"แก้ไขรายการ Task (อัปเดตคำอธิบาย/วันที่/สถานะ)\"\"\"\n",
    "    view_tasks(tasks)\n",
    "    if not tasks:\n",
    "        return\n",
    "        \n",
    "    # User Interaction และ Conditionals\n",
    "    try:\n",
    "        task_num = int(input(\" Enter the number of the task to edit: \")) - 1\n",
    "        if 0 <= task_num < len(tasks):\n",
    "            task_to_edit = tasks[task_num]\n",
    "            print(f\"\\nEditing: {task_to_edit}\")\n",
    "            \n",
    "            # Sub-menu สำหรับการแก้ไข\n",
    "            print(\"What do you want to change?\")\n",
    "            print(\"1. Description\")\n",
    "            print(\"2. Due Date\")\n",
    "            print(\"3. Status (Mark as Done/Pending)\")\n",
    "            \n",
    "            choice = input(\" Enter your choice (1-3): \")\n",
    "            \n",
    "            if choice == '1':\n",
    "                new_desc = input(\" Enter new description: \").strip()\n",
    "                if new_desc:\n",
    "                    task_to_edit.update_description(new_desc)\n",
    "                    print(\" Description updated.\")\n",
    "            elif choice == '2':\n",
    "                new_date = input(\" Enter new due date (YYYY-MM-DD, optional): \").strip()\n",
    "                if new_date:\n",
    "                    try:\n",
    "                        datetime.strptime(new_date, \"%Y-%m-%d\")\n",
    "                        task_to_edit.update_due_date(new_date)\n",
    "                        print(\" Due date updated.\")\n",
    "                    except ValueError:\n",
    "                        print(\" Invalid date format. No changes made.\")\n",
    "            elif choice == '3':\n",
    "                current_status = task_to_edit.is_completed()\n",
    "                task_to_edit.mark_completed(not current_status)\n",
    "                print(f\" Task status changed to: {'DONE' if not current_status else 'PENDING'}.\")\n",
    "            else:\n",
    "                print(\" Invalid choice. No changes made.\")\n",
    "                \n",
    "            save_tasks(tasks)\n",
    "        else:\n",
    "            print(\" Invalid task number.\")\n",
    "    except ValueError:\n",
    "        print(\" Invalid input. Please enter a number.\")\n",
    "\n",
    "def delete_task(tasks):\n",
    "    \"\"\"ลบ Task ออกจากรายการ\"\"\"\n",
    "    view_tasks(tasks)\n",
    "    if not tasks:\n",
    "        return\n",
    "    \n",
    "    try:\n",
    "        task_num = int(input(\" Enter the number of the task to delete: \")) - 1\n",
    "        if 0 <= task_num < len(tasks):\n",
    "            deleted_task = tasks.pop(task_num)\n",
    "            print(f\" Task '{deleted_task.get_description()}' deleted.\")\n",
    "            save_tasks(tasks)\n",
    "        else:\n",
    "            print(\" Invalid task number.\")\n",
    "    except ValueError:\n",
    "        print(\" Invalid input. Please enter a number.\")\n",
    "        \n",
    "# ==============================================================================\n",
    "# 4. Main Menu and Execution (60%)\n",
    "# ==============================================================================\n",
    "\n",
    "def main_menu(tasks):\n",
    "    \"\"\"แสดงเมนูหลักและรับการโต้ตอบจากผู้ใช้\"\"\"\n",
    "    \n",
    "    while True: # Loop หลักของโปรแกรม\n",
    "        print(\"\\n==========  To-Do List Manager ==========\")\n",
    "        print(\"1. Add Task\")\n",
    "        print(\"2. View Tasks\")\n",
    "        print(\"3. Edit/Update Task\")\n",
    "        print(\"4. Delete Task\")\n",
    "        print(\"5. Exit and Save\")\n",
    "        print(\"============================================\")\n",
    "        \n",
    "        choice = input(\" Enter your choice (1-5): \")\n",
    "        \n",
    "        # Conditionals\n",
    "        if choice == '1':\n",
    "            add_task(tasks)\n",
    "        elif choice == '2':\n",
    "            view_tasks(tasks)\n",
    "        elif choice == '3':\n",
    "            edit_task(tasks)\n",
    "        elif choice == '4':\n",
    "            delete_task(tasks)\n",
    "        elif choice == '5':\n",
    "            # บันทึกข้อมูลอีกครั้งก่อนออก\n",
    "            if save_tasks(tasks):\n",
    "                print(\"\\n All tasks saved. Exiting application. Goodbye!\")\n",
    "                break\n",
    "            else:\n",
    "                print(\"\\n Failed to save. Please check the error above.\")\n",
    "        else:\n",
    "            print(\" Invalid choice. Please enter a number between 1 and 5.\")\n",
    "\n",
    "# Entry point ของโปรแกรม\n",
    "if __name__ == \"__main__\":\n",
    "    # โหลดข้อมูลเมื่อเริ่มต้น\n",
    "    todo_list = load_tasks()\n",
    "    main_menu(todo_list)"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": None,
=======
   "execution_count": None,
>>>>>>> 14b7a13 (FEAT: Implement Task class with encapsulation, getters, and serialization (to/from dict).)
   "id": "67da7c06-7ea8-46a1-927e-2521a04ab8b1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
